### PR TITLE
use doors.get(pos) to determine whether a door is open

### PR DESCRIPTION
**Pull request by theFox6**
with doors.get(pos) we get an object that tells us various tings about the door at a certain position

### CODE REVIEW

**Comment by MarkuBu** [comment]
I didn't test it yet, but from a short code review I think this doesn't work. Not sure what the state function really returns and it seems that it needs a player object.

Will try it ASAP

**Comment by theFox6** [comment]
it is defined in minetest_game/doors/init.lua:
the get function returns an object to a door object or nil

**Comment by MarkuBu** [comment]
I saw this function, but I'm not really sure if it really works in any situation for the pathfinder

**Comment by theFox6** [comment]
The state function needs a door object as argument and returns true for open and false for closed.
In my code the door object is given by the ":" connection.

**Comment by theFox6** [comment]
> I'm not really sure if it really works in any situation for the pathfinder  

why not?

**Comment by MarkuBu** [comment]
Because it assumes, that the door is placed in a certain way into the world. You can place a door in the closed state, but in reality you can walk through. With my algorithm it doesn't matter how a door is placed. You can only find a path if the door is really open

**Comment by theFox6** [comment]
actually you can never say that a door is not an obstacle, you can only say which sides of it are passable

**Pull request closed without merging**
