### PR TITLE
Find paths through doors

### PR DESCRIPTION
**Pull request by theFox6**
doors will not be counted as obstacle if `ignoreDoors` is true

### CODE REVIEW

**Comment by MarkuBu** [comment]
Thanks for the PR, but I implement my own version and now I'm able to detect if doors are open or closed

**Comment by theFox6** [comment]
In my opinion the method should have an argument whether the doors should always be seen as walkable.
Some NPCs can open doors and they probably want to route through them even if they are closed.

**Comment by MarkuBu** [comment]
I think it is not the job of pathfinder to find non existing path. This should be done in the "AI". A NPC should memorize positions where it want's to walk and find and memorize doors. If the NPC can't find a way from position "a" to "b" than the NPC should find a path from "a" to the next door first, open it and than continue to "b" by finding a new path from the door to "b".

**Comment by theFox6** [comment]
> than the NPC should find a path from "a" to the next door first

... and if its the door of the wrong house/room?

**Comment by MarkuBu** [comment]
I think, the NPC should be intelligent enough to learn and memorize the right doors. And even with "the door is always open" option you don't have the guarantee that the NPC finds the right way.

You can use the A* algorithm to find a way through doors for example. The pathfinder itself uses this algorithm to find a path, but instead of searching from node to node you search form door to door. A* is not specialized for finding nodes, it can be used to find the shortest way in many other structures.

If the NPC always spawns in his habitat he can search and memorize the doors of his habitat to find a way back.

There are many ways to solve this. Of course, you can just define a door as "always open" and it would be probably the easiest option, but it is the most worse solution. For example if the pathfinder finds a path through a door, but NPC can't open the door because it is protected, you are not able to find another path because the pathfinder always returns the same path

**Pull request closed without merging**
